### PR TITLE
Add logging customization script for Segment. Closes #2.

### LINKED ISSUE #2: Event data does not adhere to Splunk Logging Best Practices
Currently this modular input sends data to Splunk with a payload in the following basic shape:

``` json
{"push_status": {}, "body": "", "timeout": 60, "id": "6252861133115955122", "reserved_count": 1}
```

The above does not adhere to Splunk's [logging best practices](http://dev.splunk.com/view/logging-best-practices/SP-CAAADP6) in that it does not include `timestamp`.

Rather than simply adding a `timestamp` it seems more appropriate to allow users of this modular input the ability to create a custom python script to **transform event data** [while writing events to the queue](https://github.com/iron-io/splunk-ironmq-mi/blob/4f30070c93abcf4170a248dd24c65d85f3b8001b/bin/splunk-ironmq-mi.py#L150-L161). To this end I've created a custom fork [with an example transform script](https://github.com/jhabdas/splunk-ironmq-segment-mi/blob/c095b6dabf2566f5ab2af846042798841801f526/bin/splunk-ironmq-segment-mi.py#L198) integrated.

Would it be possible to make something extensible we can use to transform data without hacking the modular input script at `/bin/splunk-ironmq-mi.py`?

### PR DESCRIPTION
**Pull request by ghost**
Provides the ability for users of this modular input to create custom data transforms before data is loaded into Splunk. Includes example using Segment payloads and in accordance with Splunk [Logging Best Practices](http://dev.splunk.com/view/logging-best-practices/SP-CAAADP6).

@john-paul-keenan /cc @treeder for review. Note this is my first time writing Python and my first time working with Splunk Modular Inputs.

### CODE REVIEW

**Comment by treeder** [comment]
@ulandj can you review please?

**Comment by ulandj** [comment]
hi @jhabdas ,
Your transform_data method is intended only for the Segment. for others it will not work unfortunately...

the main purpose of this plugin is to create a bridge between IronMQ and splunk enterprise framework. i.e. just get message from IronMQ queue and pass it to Splunk.
we can't parse a message body as users need. because message bodies are different(may contain json, xml, string etc.) and it is difficult to make a general template for this.
if you need an another message format feel free to edit the source code and use it.

Thanks

**Comment by ghost** [comment]
Thanks for taking a look, Ulan. You saw the script is disabled by default and requires the manual configuration step added to the README, correct? As a result, there would be no side effects or breaking changes for existing users. What all users would gain, however, is a clear way to deal with #2 when they encounter it. And given the constraints of the Splunk UI I see no other immediate solve for the problem at hand. Do you?

**Comment by ghost** [comment]
I guess it doesn't really matter. The breadcrumb is here now for others to follow. On my end I'm no longer confident our Segment Iron.io integration was a good choice over writing directly to SNS or the like and finding a way to leverage the AWS Splunk add-on instead.

Thanks to the Iron team for the help they've provided, but maintaining a custom modular input feels like a hack and necessitates a new direction and additional work.

**Pull request closed without merging**
